name: Java CI

on: push  # Run this workflow when code is pushed

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Get the code from GitHub

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Install Java 17

      - name: Compile Java Code
        run: javac Main.java  # Compile Main.java

      - name: Run Java Program
        run: java Main  # Execute the program
